spring:
  application:
    name: spring-boot-starter-kit
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
